import { MainAppShell } from '@/app/_components/MainAppShell'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface Props {
  children: React.ReactNode
}

const RootLayout = async (props: Props) => {
  const { children } = props;
  return (
    <MainAppShell>
      {children}
    </MainAppShell>
  )
}

export default RootLayout;
