import StyleProvider from '@/components/Providers/Style'
import { MainAppShell } from './_components/MainAppShell'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body>
        <StyleProvider>
          <MainAppShell>
            {children}
          </MainAppShell>
        </StyleProvider>
      </body>
    </html>
  )
}
