import { StyleProvider } from '@/components/Providers/Style'
import { AuthProvider } from '@/components/Providers/Auth'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body>
        <StyleProvider>
          <AuthProvider>
            {children}
          </AuthProvider>
        </StyleProvider>
      </body>
    </html>
  )
}
