
import StyleProvider from '@/components/Providers/Style'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body>
        <StyleProvider>
          {children}
        </StyleProvider>
      </body>
    </html>
  )
}
