query GetLoginUser {
  getUser(input: {}) {
    id
    name
    email
    role
  }
}

mutation updateLoginUser($input: UserInput!) {
  updateUser(input: {data: $input}) {
    id
    name
    email
    role
  }
}
