fragment UserFragment on User {
    id
    userId
    name
    email
    role
}

query GetLoginUser {
    user(input: {}) {
        ...UserFragment
    }
}

mutation UpdateLoginUser($input: UserInput!) {
    updateUser(input: {data: $input}) {
        ...UserFragment
    }
}
