mutation UpdateUserAvatar($nodeId: ID!, $imagePath: String!){
    updateUserDataCollection(filter: {nodeId: {eq: $nodeId}}, set: {image: $imagePath}) {
        records {
            nodeId
            image
        }
    }
}
