import { getServerSession } from 'next-auth';
import React from 'react';

import { MainAppShell } from 'app/_components/MainAppShell';
import { authOptions } from 'lib/nextAuth';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface Props {
  children: React.ReactNode
}

const RootLayout = async(props: Props) => {
  const { children } = props;
  const session = await getServerSession(authOptions);
  return (
    <MainAppShell noNavbar session={session ?? undefined}>
      {children}
    </MainAppShell>
  );
};

export default RootLayout;
