import { MainAppShell } from '@/app/_components/MainAppShell'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <MainAppShell noNavbar>
      {children}
    </MainAppShell>
  )
}
